### ISSUE TITLE
iOS shortcuts request

### ISSUE THREAD

**Issue by xyjigsaw** [WangGuibin/ImageBed#1]
求一个iOS 图床 shortcuts的捷径分享链接，感谢。
[来源](https://www.cnblogs.com/wgb1234/p/13660900.html)

**Comment by WangGuibin** [comment]
你自己建个repo，修改一下参数
https://www.icloud.com/shortcuts/683ca0b892ef41c388d3a580d15f2ab9



发自我的iPhone


------------------ Original ------------------
From: Reacubeth ***@***.***&gt;
Date: Wed,Mar 2,2022 3:05 PM
To: WangGuibin/ImageBed ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [WangGuibin/ImageBed] iOS shortcuts request (Issue #1)





 
求一个iOS 图床 shortcuts的捷径分享链接，感谢。
 来源
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xyjigsaw** [comment]
感谢楼主，我换成到了Gitee很好用。
